language: node_js
node_js:
- 4.2.4
deploy:
  provider: npm
  email: npm@lossless.digital
  api_key:
    secure: VrsMzTKpowxv/dTNt/ojpDilk6bpXpkHn5izB3RZZRFDRW6VnhcNhX1hIjeFiHwLcnHq94FQBwroaAuIWhVZ4boTIz2V9n5hv0SElbIgfERnwa94SsGAJYcDDgdYIXfShgnd2TvRlG3QzjBLZPYgYjZWrlGmyi73W5nRU1RIFWDr9/V8sJC5w/2nHiIcfbrkABYNs13VERS9VkQW++CYdc9kNf/OFprSM7iY/OP3gNqJaNR2jrLVpLp6W3tQrL4ZPbAQvPEAMw0Pz8L4xrwZzMqJb9LxVPaXBnUsIWcSS2znnmjbijQ9tY3RTAmIpMF0ZGNHcjEji04k7Jg1ZcIwR/OVqetbtIFTnks+gojXuFKegDkgb5SSYRY88vT5HkhhkOuAcSAU1QYosisprHgPUR0ifN8ovbJzdnO+ByZuPrLSd1sOz51LzT4gD8fVfKqIrYM5a2wA1VOkF1tMc2EIuUFTW0X85Iry0QDMmsNgGJ4LIe2vBcKN9FSkoDDmx/5FJ8X31ifGXvWyow7Ta4cgK76uNAk7VfqpC/MrohBWrxzH8LRsIzmHoHUq0/BgfuXL5LMUfDzx1IhlASCnPGKNEv+gROE0tDZR9xVG5ean7Z/IrQHxFueS29U+rKcgJyjuvYERwCJMpoj0sNidrn0m0KqQNftNw/txb0U9cR2955I=
  on:
    tags: true
    repo: UmbrellaZone/umbrella-legal
notifications:
  slack:
    secure: oM8yCioyO48J/6mLxZxn6UhGw0AcV6FJbPoSUfrXtFIB6/CyuUROoUx4KbDyaECzQfmPcISfms5q8KV3a9/k3qZNAK4HFD8Jbd0Hk1e/XdMJNQ8skF1pOiK/LKnydBaULx4EtXUaPx0d75V9+gvYZmQOJHUbeQci1Xl45zJGW8kQqxDLA3GnW/BzcxIIqexmtLTi6Aw0YpYOfv+pjgHovUuzeVG/y/5B46YCui/3N+Og+i4Ka8pU84c0B/D5O3PqfwfwD3RU5dwdLp+8xCF+HgW6X1dXKbH7EWJUG62MHTMAvmr20+rUGGNIoX2mZyrtnDvayFh4LjbSR5ifMUpl8DXDOF2iGoyTd+97KGtMJNEvmkQdN/44m5Vd+ov+kNOOx5ZldmcGWBZwi8dGigAZ3h1q9FVqfKsd3ZtRgCvikMwFhbXLipeuTKRpNC35Zg6Fdi56UfI36ueR59Aa0CCB54QRcrZqaiG7xNU7vjWbqUJAuFwXH7JtGvZRVhrW2nGXBQ/x7tsCkdol4Ci+wXXXmb8nB3UtjqoCQITjs4chHuP//Fv+KDL9IhEsNNF8czrs3BKbcITBuIcEE1VgXfoMdO8LzcFFwWJOQ8J7d68Dll+3mth/8jmwTt2kxX1Gbin5NzeYKLz0OP9I3aBhhTX6VrKbcbdUHX3kqay8BTl9Q+s=
